### ISSUE TITLE
Something wrong about aarch64-softmmu

### ISSUE THREAD

**Issue by securebluefox** [thebabush/honggfuzz-qemu#2]
When I execute the `make` command in the honggfuzz-qemu directory, I receive the following error:
![](http://img.lhyerror404.cn/error404/2020-06-19-145131.png)
How should i fix it？

**Comment by thebabush** [comment]
You are trying to build the system emulator (`*-softmmu`). Honggfuzz + qemu_mode only works with linux-user.

If you want to fuzz aarch64 binaries in userspace, build with `TARGETS=aarch64-linux-user make`.
