### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by Ben-Lichtman** [thebabush/honggfuzz-qemu#3]
I am  trying to use this with honggfuzz's instructions - cding into the repo and running make, but I then encounter this error:

> /home/ben/repos/fuzzing/honggfuzz/qemu_mode/honggfuzz-qemu/linux-user/syscall.c: In function ‘do_syscall1’:
> /home/ben/repos/fuzzing/honggfuzz/qemu_mode/honggfuzz-qemu/linux-user/syscall.c:7661:30: error: implicit declaration of function ‘stime’; did you mean ‘utime’? [-Werror=implicit-function-declaration]
>  7661 |             return get_errno(stime(&host_time));
>       |                              ^~~~~
>       |                              utime
> /home/ben/repos/fuzzing/honggfuzz/qemu_mode/honggfuzz-qemu/linux-user/syscall.c:7661:30: error: nested extern declaration of ‘stime’ [-Werror=nested-externs]
> cc1: all warnings being treated as errors
> make[1]: *** [/home/ben/repos/fuzzing/honggfuzz/qemu_mode/honggfuzz-qemu/rules.mak:69: linux-user/syscall.o] Error 1
> make: *** [Makefile:472: i386-linux-user/all] Error 2

**Comment by thebabush** [comment]
This is weird. What's your OS?

**Comment by Ben-Lichtman** [comment]
Arch linux :p

I am using the makefile from honggfuzz but have changed the targets to 
`TARGETS ?= i386-linux-user x86_64-linux-user arm-linux-user mips-linux-user`
Though that doesn't seem to make much difference

**Comment by Ben-Lichtman** [comment]
I changed the (deprecated) stime call with clock_settime and it built properly.

See description in: https://man7.org/linux/man-pages/man2/stime.2.html
