### ISSUE TITLE
Readme should explain how this is different to regular qemu user mode

### ISSUE THREAD

**Issue by Ben-Lichtman** [thebabush/honggfuzz-qemu#4]
It is pretty unclear exactly why we should be using this over normal qemu - does this add extra instrumentation that qemu doesn't have? Is honggfuzz not able to look inside regular qemu at all, or does this version just make it better? What are the patches that have been applied?

**Comment by thebabush** [comment]
1. https://github.com/google/AFL/tree/master/qemu_mode
2. you can git diff between master and honggfuzz

**Comment by Ben-Lichtman** [comment]
so this is identical to the AFL qmu patch?

**Comment by thebabush** [comment]
It serves the same purpose with a near-identical approach. The main difference is that this implementation is not as good as AFL's (as in, it needs more effort but atm I have other stuff to do).
